### ISSUE TITLE
OTel Q&A with Ariel Valentin

### ISSUE THREAD

**Issue by avillela** [open-telemetry/sig-end-user#84]
### Date and time for the session

Thursday, December 12th, 13:00 EST/10:00 PST

### Description used for promotional posts and event descriptions

TBD

### Tasks

- [x] Confirm speakers (@danielgblanco)
- [x] Confirm date and time (@danielgblanco)
- [x] Create [Q&A interview doc](https://docs.google.com/document/d/1hkgRJZfFAtyF-tN-DDyYSKp-jYlIXD3lp6_KWDV6lb0/edit?usp=sharing)
- [x] Fill in the template fields highlighted in blue
- [x] Create promo image for socials (@reese-lee)
- [x] Create OpenTelemetry public calendar event (including Zoom link)
- [x] Create CNCF event
- [x] Set up livestream (Henrik Rexed)
- [x] Promote on OpenTelemetry socials (LinkedIn, X, Bluesky, Mastodon) - make sure that these point to the CNCF event link
- [x] Promote on CNCF Slack channels ([#otel-announcements](https://cloud-native.slack.com/archives/C049G9W5NQ7), [#otel-sig-end-users](https://cloud-native.slack.com/archives/C01RT3MSWGZ), [#o11y-ambassadors](https://cloud-native.slack.com/archives/C050WLWHV1U)) - make sure that these point to the CNCF event link
- [x] Host session -> session will be hosted by @reese-lee 
- [x] Promote recording on socials (week following livestream)

**Comment by danielgblanco** [comment]
@arielvalentin you said that any time after Dec 1st would work?

**Comment by arielvalentin** [comment]
@danielgblanco Yes after December 1st would work well. I sent a link to my calendar availability via CNCF slack DM.

**Comment by danielgblanco** [comment]
Event created on public calendar (I also cancelled the End-User SIG meeting coinciding with this). There is no Zoom link for this at the moment, but when we have the streamyard link I (or anyone with calendar permissions) can update the event.

**Comment by avillela** [comment]
* [CNCF Event](https://community.cncf.io/opentelemetry/) created,  streaming to YouTube
* [LinkedIn Stream](https://www.linkedin.com/events/7269620036485464065/about/) created

**Comment by danielgblanco** [comment]
Is there anything else to do here? I think it can be closed? I loved the session btw, so good to have it live on YouTube :) thank you to all involved!

**Comment by reese-lee** [comment]
Thanks for following up @danielgblanco! I have to follow up with Henrik about the recording (getting timestamps in and adding show notes in the description).

**Comment by danielgblanco** [comment]
@reese-lee was that done in the end?

**Comment by avillela** [comment]
Promos have been done.

**Comment by avillela** [comment]
Closing this so it doesn't linger on.
